#ifndef TESTCONNADAPTOR2_GLOBAL_H
#define TESTCONNADAPTOR2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTCONNADAPTOR2_LIBRARY)
#  define TESTCONNADAPTOR2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTCONNADAPTOR2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTCONNADAPTOR2_GLOBAL_H
